print("SEPARATOR :")
print(" ")
print('P', 'Y', 'T', 'H', 'O', 'N')
print('P', 'Y', 'T', 'H', 'O', 'N', sep='')
print('P', 'Y', 'T', 'H', 'O', 'N', sep=',')
print('P', 'Y', 'T', 'H', 'O', 'N', sep='|')
print('P', 'Y', 'T', 'H', 'O', 'N', sep='     ')
print('010', '7777', '1234', sep='-')
print('python', 'google.com', sep='@')
print(" ")
